version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '!Password123'
      MYSQL_DATABASE: RunningTrackerDb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/Running/Infra/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
