version: '3.8'

services:
  sqlserver:
    build: .
    container_name: sqlserver
    environment:
      SA_PASSWORD: "@Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./src/Running/Infra/init.sql:/tmp/init.sql
      - ./src/Running/Infra/entrypoint.sh:/tmp/entrypoint.sh

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./src/Running/Infra/init.sql:/tmp/init.sql
      - ./src/Running/Infra/entrypoint.sh:/tmp/entrypoint.sh
    command: /bin/bash /tmp/entrypoint.sh